apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: default-broker-proxy
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/n3wscott/knperf/cmd/proxy
            env:
              - name: TARGET
                value: http://default-broker.default.svc.cluster.local/