apiVersion: v1
kind: ServiceAccount
metadata:
  name: install-script
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: install-script
subjects:
  - kind: ServiceAccount
    name: install-script
    namespace: default
roleRef:
  kind: ClusterRole
  name: knperf-controller # borrow this for now, kthankx
  apiGroup: rbac.authorization.k8s.io

